# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # - path: environments/sn-health-prd-secrets.yaml
  #   kms: 'arn:aws:kms:af-south-1:767397920703:key/c5b4e3c5-bedb-4b44-8567-f0cea3e8d3f2'
  
  - path_regex: environments/azure-senegal-prod-secrets.yaml$
    azure_keyvault: "https://senegal-prod.vault.azure.net/keys/senegal-prod-master-key/6c6c382bff7f4b63b1ac12ffcbe24746"