# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path: environments/sn-health-prd-secrets.yaml
    kms: 'arn:aws:kms:af-south-1:767397920703:key/c5b4e3c5-bedb-4b44-8567-f0cea3e8d3f2'